//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsPolicy) DeepCopyInto(out *AnalyticsPolicy) {
	*out = *in
	if in.FullClientLogs != nil {
		in, out := &in.FullClientLogs, &out.FullClientLogs
		*out = new(FullClientLogs)
		(*in).DeepCopyInto(*out)
	}
	if in.UdfLogThrottle != nil {
		in, out := &in.UdfLogThrottle, &out.UdfLogThrottle
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsPolicy.
func (in *AnalyticsPolicy) DeepCopy() *AnalyticsPolicy {
	if in == nil {
		return nil
	}
	out := new(AnalyticsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendProperties) DeepCopyInto(out *BackendProperties) {
	*out = *in
	if in.AnalyticsPolicy != nil {
		in, out := &in.AnalyticsPolicy, &out.AnalyticsPolicy
		*out = new(PoolAnalyticsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AnalyticsProfileRef != nil {
		in, out := &in.AnalyticsProfileRef, &out.AnalyticsProfileRef
		*out = new(string)
		**out = **in
	}
	if in.ApplicationPersistenceProfileRef != nil {
		in, out := &in.ApplicationPersistenceProfileRef, &out.ApplicationPersistenceProfileRef
		*out = new(string)
		**out = **in
	}
	if in.DefaultServerPort != nil {
		in, out := &in.DefaultServerPort, &out.DefaultServerPort
		*out = new(int32)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HealthMonitorRefs != nil {
		in, out := &in.HealthMonitorRefs, &out.HealthMonitorRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InlineHealthMonitor != nil {
		in, out := &in.InlineHealthMonitor, &out.InlineHealthMonitor
		*out = new(bool)
		**out = **in
	}
	if in.LbAlgorithm != nil {
		in, out := &in.LbAlgorithm, &out.LbAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.LbAlgorithmHash != nil {
		in, out := &in.LbAlgorithmHash, &out.LbAlgorithmHash
		*out = new(string)
		**out = **in
	}
	if in.MinServersUp != nil {
		in, out := &in.MinServersUp, &out.MinServersUp
		*out = new(int32)
		**out = **in
	}
	if in.PkiProfileRef != nil {
		in, out := &in.PkiProfileRef, &out.PkiProfileRef
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SslKeyAndCertificateRef != nil {
		in, out := &in.SslKeyAndCertificateRef, &out.SslKeyAndCertificateRef
		*out = new(string)
		**out = **in
	}
	if in.SslProfileRef != nil {
		in, out := &in.SslProfileRef, &out.SslProfileRef
		*out = new(string)
		**out = **in
	}
	if in.UseServicePort != nil {
		in, out := &in.UseServicePort, &out.UseServicePort
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendProperties.
func (in *BackendProperties) DeepCopy() *BackendProperties {
	if in == nil {
		return nil
	}
	out := new(BackendProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullClientLogs) DeepCopyInto(out *FullClientLogs) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(int32)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullClientLogs.
func (in *FullClientLogs) DeepCopy() *FullClientLogs {
	if in == nil {
		return nil
	}
	out := new(FullClientLogs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTValidationParams) DeepCopyInto(out *JWTValidationParams) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTValidationParams.
func (in *JWTValidationParams) DeepCopy() *JWTValidationParams {
	if in == nil {
		return nil
	}
	out := new(JWTValidationParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4Rule) DeepCopyInto(out *L4Rule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4Rule.
func (in *L4Rule) DeepCopy() *L4Rule {
	if in == nil {
		return nil
	}
	out := new(L4Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L4Rule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4RuleList) DeepCopyInto(out *L4RuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L4Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4RuleList.
func (in *L4RuleList) DeepCopy() *L4RuleList {
	if in == nil {
		return nil
	}
	out := new(L4RuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L4RuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4RuleSpec) DeepCopyInto(out *L4RuleSpec) {
	*out = *in
	if in.AnalyticsPolicy != nil {
		in, out := &in.AnalyticsPolicy, &out.AnalyticsPolicy
		*out = new(AnalyticsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AnalyticsProfileRef != nil {
		in, out := &in.AnalyticsProfileRef, &out.AnalyticsProfileRef
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileRef != nil {
		in, out := &in.ApplicationProfileRef, &out.ApplicationProfileRef
		*out = new(string)
		**out = **in
	}
	if in.BackendProperties != nil {
		in, out := &in.BackendProperties, &out.BackendProperties
		*out = make([]*BackendProperties, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BackendProperties)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DelayFairness != nil {
		in, out := &in.DelayFairness, &out.DelayFairness
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkProfileRef != nil {
		in, out := &in.NetworkProfileRef, &out.NetworkProfileRef
		*out = new(string)
		**out = **in
	}
	if in.NetworkSecurityPolicyRef != nil {
		in, out := &in.NetworkSecurityPolicyRef, &out.NetworkSecurityPolicyRef
		*out = new(string)
		**out = **in
	}
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(string)
		**out = **in
	}
	if in.SecurityPolicyRef != nil {
		in, out := &in.SecurityPolicyRef, &out.SecurityPolicyRef
		*out = new(string)
		**out = **in
	}
	if in.ServerNetworkProfileRef != nil {
		in, out := &in.ServerNetworkProfileRef, &out.ServerNetworkProfileRef
		*out = new(string)
		**out = **in
	}
	if in.SslKeyAndCertificateRefs != nil {
		in, out := &in.SslKeyAndCertificateRefs, &out.SslKeyAndCertificateRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SslProfileRef != nil {
		in, out := &in.SslProfileRef, &out.SslProfileRef
		*out = new(string)
		**out = **in
	}
	if in.VsDatascriptRefs != nil {
		in, out := &in.VsDatascriptRefs, &out.VsDatascriptRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4RuleSpec.
func (in *L4RuleSpec) DeepCopy() *L4RuleSpec {
	if in == nil {
		return nil
	}
	out := new(L4RuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4RuleStatus) DeepCopyInto(out *L4RuleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4RuleStatus.
func (in *L4RuleStatus) DeepCopy() *L4RuleStatus {
	if in == nil {
		return nil
	}
	out := new(L4RuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthAppSettings) DeepCopyInto(out *OAuthAppSettings) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
	if in.OidcConfig != nil {
		in, out := &in.OidcConfig, &out.OidcConfig
		*out = new(OIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthAppSettings.
func (in *OAuthAppSettings) DeepCopy() *OAuthAppSettings {
	if in == nil {
		return nil
	}
	out := new(OAuthAppSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthResourceServer) DeepCopyInto(out *OAuthResourceServer) {
	*out = *in
	if in.AccessType != nil {
		in, out := &in.AccessType, &out.AccessType
		*out = new(string)
		**out = **in
	}
	if in.IntrospectionDataTimeout != nil {
		in, out := &in.IntrospectionDataTimeout, &out.IntrospectionDataTimeout
		*out = new(int32)
		**out = **in
	}
	if in.JwtParams != nil {
		in, out := &in.JwtParams, &out.JwtParams
		*out = new(JWTValidationParams)
		(*in).DeepCopyInto(*out)
	}
	if in.OpaqueTokenParams != nil {
		in, out := &in.OpaqueTokenParams, &out.OpaqueTokenParams
		*out = new(OpaqueTokenValidationParams)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthResourceServer.
func (in *OAuthResourceServer) DeepCopy() *OAuthResourceServer {
	if in == nil {
		return nil
	}
	out := new(OAuthResourceServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthSamlConfig) DeepCopyInto(out *OAuthSamlConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthSamlConfig.
func (in *OAuthSamlConfig) DeepCopy() *OAuthSamlConfig {
	if in == nil {
		return nil
	}
	out := new(OAuthSamlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuthSamlConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthSamlConfigList) DeepCopyInto(out *OAuthSamlConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OAuthSamlConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthSamlConfigList.
func (in *OAuthSamlConfigList) DeepCopy() *OAuthSamlConfigList {
	if in == nil {
		return nil
	}
	out := new(OAuthSamlConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAuthSamlConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthSamlConfigSpec) DeepCopyInto(out *OAuthSamlConfigSpec) {
	*out = *in
	if in.Fqdn != nil {
		in, out := &in.Fqdn, &out.Fqdn
		*out = new(string)
		**out = **in
	}
	if in.OauthVsConfig != nil {
		in, out := &in.OauthVsConfig, &out.OauthVsConfig
		*out = new(OAuthVSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SamlSpConfig != nil {
		in, out := &in.SamlSpConfig, &out.SamlSpConfig
		*out = new(SAMLSPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SsoPolicyRef != nil {
		in, out := &in.SsoPolicyRef, &out.SsoPolicyRef
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthSamlConfigSpec.
func (in *OAuthSamlConfigSpec) DeepCopy() *OAuthSamlConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OAuthSamlConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthSamlConfigStatus) DeepCopyInto(out *OAuthSamlConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthSamlConfigStatus.
func (in *OAuthSamlConfigStatus) DeepCopy() *OAuthSamlConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OAuthSamlConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthSettings) DeepCopyInto(out *OAuthSettings) {
	*out = *in
	if in.AppSettings != nil {
		in, out := &in.AppSettings, &out.AppSettings
		*out = new(OAuthAppSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthProfileRef != nil {
		in, out := &in.AuthProfileRef, &out.AuthProfileRef
		*out = new(string)
		**out = **in
	}
	if in.ResourceServer != nil {
		in, out := &in.ResourceServer, &out.ResourceServer
		*out = new(OAuthResourceServer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthSettings.
func (in *OAuthSettings) DeepCopy() *OAuthSettings {
	if in == nil {
		return nil
	}
	out := new(OAuthSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthVSConfig) DeepCopyInto(out *OAuthVSConfig) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.CookieTimeout != nil {
		in, out := &in.CookieTimeout, &out.CookieTimeout
		*out = new(int32)
		**out = **in
	}
	if in.LogoutUri != nil {
		in, out := &in.LogoutUri, &out.LogoutUri
		*out = new(string)
		**out = **in
	}
	if in.OauthSettings != nil {
		in, out := &in.OauthSettings, &out.OauthSettings
		*out = make([]*OAuthSettings, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(OAuthSettings)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.PostLogoutRedirectUri != nil {
		in, out := &in.PostLogoutRedirectUri, &out.PostLogoutRedirectUri
		*out = new(string)
		**out = **in
	}
	if in.RedirectUri != nil {
		in, out := &in.RedirectUri, &out.RedirectUri
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthVSConfig.
func (in *OAuthVSConfig) DeepCopy() *OAuthVSConfig {
	if in == nil {
		return nil
	}
	out := new(OAuthVSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfig) DeepCopyInto(out *OIDCConfig) {
	*out = *in
	if in.OidcEnable != nil {
		in, out := &in.OidcEnable, &out.OidcEnable
		*out = new(bool)
		**out = **in
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(bool)
		**out = **in
	}
	if in.Userinfo != nil {
		in, out := &in.Userinfo, &out.Userinfo
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfig.
func (in *OIDCConfig) DeepCopy() *OIDCConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpaqueTokenValidationParams) DeepCopyInto(out *OpaqueTokenValidationParams) {
	*out = *in
	if in.ServerID != nil {
		in, out := &in.ServerID, &out.ServerID
		*out = new(string)
		**out = **in
	}
	if in.ServerSecret != nil {
		in, out := &in.ServerSecret, &out.ServerSecret
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpaqueTokenValidationParams.
func (in *OpaqueTokenValidationParams) DeepCopy() *OpaqueTokenValidationParams {
	if in == nil {
		return nil
	}
	out := new(OpaqueTokenValidationParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolAnalyticsPolicy) DeepCopyInto(out *PoolAnalyticsPolicy) {
	*out = *in
	if in.EnableRealtimeMetrics != nil {
		in, out := &in.EnableRealtimeMetrics, &out.EnableRealtimeMetrics
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolAnalyticsPolicy.
func (in *PoolAnalyticsPolicy) DeepCopy() *PoolAnalyticsPolicy {
	if in == nil {
		return nil
	}
	out := new(PoolAnalyticsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLSPConfig) DeepCopyInto(out *SAMLSPConfig) {
	*out = *in
	if in.AcsIndex != nil {
		in, out := &in.AcsIndex, &out.AcsIndex
		*out = new(int32)
		**out = **in
	}
	if in.AuthnReqAcsType != nil {
		in, out := &in.AuthnReqAcsType, &out.AuthnReqAcsType
		*out = new(string)
		**out = **in
	}
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.CookieTimeout != nil {
		in, out := &in.CookieTimeout, &out.CookieTimeout
		*out = new(int32)
		**out = **in
	}
	if in.EntityId != nil {
		in, out := &in.EntityId, &out.EntityId
		*out = new(string)
		**out = **in
	}
	if in.SigningSslKeyAndCertificateRef != nil {
		in, out := &in.SigningSslKeyAndCertificateRef, &out.SigningSslKeyAndCertificateRef
		*out = new(string)
		**out = **in
	}
	if in.SingleSignonUrl != nil {
		in, out := &in.SingleSignonUrl, &out.SingleSignonUrl
		*out = new(string)
		**out = **in
	}
	if in.UseIdpSessionTimeout != nil {
		in, out := &in.UseIdpSessionTimeout, &out.UseIdpSessionTimeout
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLSPConfig.
func (in *SAMLSPConfig) DeepCopy() *SAMLSPConfig {
	if in == nil {
		return nil
	}
	out := new(SAMLSPConfig)
	in.DeepCopyInto(out)
	return out
}
