/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pkg/apis/ako/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOAuthSamlConfigs implements OAuthSamlConfigInterface
type FakeOAuthSamlConfigs struct {
	Fake *FakeAkoV1alpha2
	ns   string
}

var oauthsamlconfigsResource = schema.GroupVersionResource{Group: "ako.vmware.com", Version: "v1alpha2", Resource: "oauthsamlconfigs"}

var oauthsamlconfigsKind = schema.GroupVersionKind{Group: "ako.vmware.com", Version: "v1alpha2", Kind: "OAuthSamlConfig"}

// Get takes name of the oAuthSamlConfig, and returns the corresponding oAuthSamlConfig object, and an error if there is any.
func (c *FakeOAuthSamlConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.OAuthSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(oauthsamlconfigsResource, c.ns, name), &v1alpha2.OAuthSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.OAuthSamlConfig), err
}

// List takes label and field selectors, and returns the list of OAuthSamlConfigs that match those selectors.
func (c *FakeOAuthSamlConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.OAuthSamlConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(oauthsamlconfigsResource, oauthsamlconfigsKind, c.ns, opts), &v1alpha2.OAuthSamlConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.OAuthSamlConfigList{ListMeta: obj.(*v1alpha2.OAuthSamlConfigList).ListMeta}
	for _, item := range obj.(*v1alpha2.OAuthSamlConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oAuthSamlConfigs.
func (c *FakeOAuthSamlConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(oauthsamlconfigsResource, c.ns, opts))

}

// Create takes the representation of a oAuthSamlConfig and creates it.  Returns the server's representation of the oAuthSamlConfig, and an error, if there is any.
func (c *FakeOAuthSamlConfigs) Create(ctx context.Context, oAuthSamlConfig *v1alpha2.OAuthSamlConfig, opts v1.CreateOptions) (result *v1alpha2.OAuthSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(oauthsamlconfigsResource, c.ns, oAuthSamlConfig), &v1alpha2.OAuthSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.OAuthSamlConfig), err
}

// Update takes the representation of a oAuthSamlConfig and updates it. Returns the server's representation of the oAuthSamlConfig, and an error, if there is any.
func (c *FakeOAuthSamlConfigs) Update(ctx context.Context, oAuthSamlConfig *v1alpha2.OAuthSamlConfig, opts v1.UpdateOptions) (result *v1alpha2.OAuthSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(oauthsamlconfigsResource, c.ns, oAuthSamlConfig), &v1alpha2.OAuthSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.OAuthSamlConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOAuthSamlConfigs) UpdateStatus(ctx context.Context, oAuthSamlConfig *v1alpha2.OAuthSamlConfig, opts v1.UpdateOptions) (*v1alpha2.OAuthSamlConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(oauthsamlconfigsResource, "status", c.ns, oAuthSamlConfig), &v1alpha2.OAuthSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.OAuthSamlConfig), err
}

// Delete takes name of the oAuthSamlConfig and deletes it. Returns an error if one occurs.
func (c *FakeOAuthSamlConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(oauthsamlconfigsResource, c.ns, name), &v1alpha2.OAuthSamlConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOAuthSamlConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(oauthsamlconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.OAuthSamlConfigList{})
	return err
}

// Patch applies the patch and returns the patched oAuthSamlConfig.
func (c *FakeOAuthSamlConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.OAuthSamlConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(oauthsamlconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha2.OAuthSamlConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.OAuthSamlConfig), err
}
