apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "hostrules.ako.k8s.io"
spec:
  group: "ako.k8s.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "hostrules"
    singular: "hostrule"
    kind: "HostRule"
    shortNames:
      - "hostrule"
      - "hr"
  subresources:
    status: {}
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - virtualhost
          properties:
            virtualhost:
              type: object
              required:
              - fqdn
              properties:
                fqdn:
                  type: string
                tls:
                  type: object
                  required:
                  - sslKeyCertificate
                  properties:
                    termination:
                      type: string
                      enum:
                        - edge
                    sslKeyCertificate:
                      type: object
                      required:
                      - name
                      - type
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                          enum:
                            - ref
                wafPolicy:
                  type: string
                applicationProfile:
                  type: string
                httpPolicy:
                  type: object
                  properties:
                    policySets:
                      type: array
                      items:
                        type: string
                    overwrite:
                      type: boolean
        status:
          type: object
          properties:
            status:
              type: string
            error:
              type: string
  additionalPrinterColumns:
  - name: Host
    type: string
    description: virtualhost for which the hostrule is valid
    JSONPath: .spec.virtualhost.fqdn
  - name: Status
    type: string
    description: status of the hostrule object
    JSONPath: .status.status
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
